#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  blueman-manager
fi

STATUS=$(bluetooth | grep -wo 'off\|on')

ON=
OFF=

case "${STATUS}" in
  "on")
    echo "$ON"
    echo "$ON"
    echo "" ;;
  "off")
    echo "$OFF"
    echo "$OFF"
    echo "" ;;
esac
