#!/bin/bash

URGENT_VALUE=25
PACKAGE_COUNT=$(($(apt list --upgradeable 2> /dev/null | wc -l) - 1))

if [[ "${PACKAGE_COUNT}" -gt 0 ]]; then
  echo "${PACKAGE_COUNT}" # full-text
  echo "${PACKAGE_COUNT}" # short-text
  echo ""
  if [[ "${PACKAGE_COUNT}" -gt "${URGENT_VALUE}" ]]; then
    exit 33
  fi
fi
