#!/bin/bash

HAS_WIRELESS=$(iwconfig 2>&1 | grep -v 'no wireless' | tr -d ' ' | tr -d '\n')

if [[ "${HAS_WIRELESS}" == "" ]]; then
  exit
fi

SSID_NAME=$(iwgetid -r)

case $BLOCK_BUTTON in
  1) urxvt -name nmtui -g 80x25-0-60 -e nmtui;;
esac
# You can put any urgent name so the block will give warning
# if a network with this name is used, like public wifi or alike.
# You can separate multiple values with \|
URGENT_VALUE=""

if [[ "${SSID_NAME}" != "" ]]; then
  echo "${SSID_NAME}"
  echo "${SSID_NAME}"
  echo ""

  if [[ "${URGENT_VALUE}" != "" ]] && [[ $(echo "${SSID_NAME}" | grep -we "${URGENT_VALUE}") != "" ]]; then
    exit 33
  fi
else
  echo "DISCONNECTED"
  echo "DISCONNECTED"
  echo ""
fi
